apiVersion: v1
kind: Service
metadata:
  name: nginx-1
  labels:
    app: nginx-1
spec:
  type: NodePort
  ports:
  - port: 80
    name: nginx-php-1
    targetPort: 80
    nodePort: 30391 #The range of valid ports is 30000-32767
  selector:
    app: nginx-1
---
