apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment-1
spec:
  replicas: 2
  selector:
    app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: pvc-web-1
      containers:
      - name: nginxcontainer
        image: webdevops/php-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /var/www/html
        env:
        - name: WEB_DOCUMENT_ROOT
          value: "/var/www/html"
