apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: nginx-php-1
  labels:
    app: nginx-php-1
spec:
  type: NodePort
  ports:
  - port: 80
    name: nginx-php-1
    targetPort: 80
    nodePort: 3391 #The range of valid ports is 30000-32767
  selector:
    app: nginx-php-1
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxdeployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-php-1
    spec:
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: pvc-web-1
      containers:
      - name: nginxcontainer
        image: webdevops/php-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /var/www/html
        env:
        - name: WEB_DOCUMENT_ROOT
          value: "/var/www/html"
          
---

#PV_01
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-1
  labels:
    data: www
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.204.184
    path: "/mnt/nfs_share/web_1"
---

#PVC_01
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web-1
spec:
  selector:
    matchLabels:
       data: www
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
